config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  get "/pages/:page" => "pages#show", :controller => 'pages', :action => 'show', :as => 'my_page'

  devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }, :path_prefix => 'd'
  #devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  resources :users, :only =>[:show]
  resources :posts
  resources :friends, only: [:index, :create]
  
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :posts do
    resources :likes, :comments
  end
  
  post "/friends/accept" => "friends/accept"
  post "/friends/decline" => "friends/decline"
  post "/friends/remove" => "friends/remove"
  post "/friends/block" => "friends/block"
  post "/friends/unblock" => "friends/unblock"


 
  


end




#resources friends?

app/models/notification.rb
class Notification < ApplicationRecord

    belongs_to :recipient, class_name: "User"
    belongs_to :actor, class_name: "User"
    belongs_to :notifiable, polymorphic: true


    scope :unread, ->{ where(read_at: nil) }
    scope :recent, ->{ order(created_at: :desc).limit(5) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
    before_action :authenticate_user!

    def index
        @user = current_user
        @notifications = Notification.where(recipient: current_user).unread
        #@notification = Notification.find(params[:id])
        #@actor = User.find(params[id: @notification.actor_id])
    end

    def mark_as_read
        @notification = Notification.find(params[:id])
        @notification.update(read_at: Time.zone.now)
        redirect_to notifications_path
    end


end

app/views/notifications/index.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
    </div>
    <div class="col-sm-6">
        <div class="row mb-3">

            <% @notifications.each do |n| %>
                <div class="card mb-3"> 
                    <div class= "row mt-1 mb-1">
                      <%if n.action == "commented"%>
                      <span>
                        <strong><%=link_to n.actor.name, user_path(id: n.actor_id), class: "deco-none"%></strong>
                        <%="#{n.action} on your"%> <strong><%=link_to n.notifiable_type, post_path(id: n.notifiable_id)%></strong>
                      </span>

                      <% elsif n.action == "liked"%>
                      <span>
                        <strong><%=link_to n.actor.name, user_path(id: n.actor_id), class: "deco-none"%></strong>
                        <%= "#{n.action} your " %><strong><%=link_to n.notifiable_type, post_path(id: n.notifiable_id)%></strong>
                      </span>

                      <% elsif n.action == "accepted your friend request"%>
                      <span>
                        <strong><%=link_to n.actor.name, user_path(id: n.actor_id), class: "deco-none"%></strong><%= " #{n.action}."%>
                      </span>
                      
                      <% elsif n.action == "sent a friend request"%>
                      <span>
                        <strong><%=link_to n.actor.name, user_path(id: n.actor_id), class: "deco-none"%></strong><%= " #{n.action}."%>
                      </span>

                      <% end %>
                    </div>
                      <small><%=link_to "Mark as Read", mark_as_read_notifications_path(id: n.id), :method=> :post, class: "deco-none"%></small>

                </div>
                <%end%>
        </div>

    </div>
    <div class="col text-center">
    </div>
  </div>
</div>