config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  get "/pages/:page" => "pages#show", :controller => 'pages', :action => 'show', :as => 'my_page'

  devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }, :path_prefix => 'd'
  #devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  resources :users, :only =>[:show]
  resources :posts
  resources :friends, only: [:index, :create]
  
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :posts do
    resources :likes, :comments
  end
  
  post "/friends/accept" => "friends/accept"
  post "/friends/decline" => "friends/decline"
  post "/friends/remove" => "friends/remove"
  post "/friends/block" => "friends/block"
  post "/friends/unblock" => "friends/unblock"


 
  


end




#resources friends?

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
        :recoverable, :rememberable, :validatable, :omniauthable,
        omniauth_providers: [:facebook]

  has_many :notifications, foreign_key: :recipient_id
  has_many :posts, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :comments, dependent: :destroy

  has_one_attached :profile_pic
  
  has_friendship

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.name = "Facebook guest ##{rand(1..1000)}"
      user.provider = auth.provider
      user.uid = auth.uid
      user.password = Devise.friendly_token[0,20]
    end
  end

  

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
    def facebook
        @user = User.from_omniauth(request.env["omniauth.auth"])
        sign_in_and_redirect @user
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = Post.new
    @posts = @user.posts
  end

  private

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:profile_pic)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_notifications.html.erb
<div class="card" style="width: 18rem;">
    <div class="card-header">
    Friend Requests
    </div>
        <ul class= "list-group list-group-flush">
            <% @user.pending_friends.each do |p| %>
            <li class = "list-group-item">
                <%="You sent a friend request to #{p.name}"%>
            <% end %>
            </li>

            <% @user.requested_friends.each do |p| %>
            <li class = "list-group-item">
                <%="#{p.name} sent you a friend request"%>
                <%= link_to "Accept Friend Request", friends_accept_path, class: "btn btn-primary" %>
                <%= link_to "Decline Friend Request", friends_decline_path, class: "btn btn-primary" %>
            <% end %>
            </li>
            

        </ul>

        

</div>

app/views/users/_profile.html.erb
<div class="card mb-1" style="max-width: 560px;">

    <div class="row no-gutters">
        <div class="col-sm-auto">
            <% if @user.profile_pic.attached? %>
            <img src="<%=(url_for(@user.profile_pic))%>", class="image-size">
            <% else %>
            <img src="https://bulma.io/images/placeholders/64x64.png">
            <% end %>
        </div>
        
        <div class="col">    
            <h5 class="card-title"><%=@user.name%></h5>
        </div>
    </div>

        <div class="card-body">
            <p class="card-text">Posts: <small class="text-muted"><%= @user.posts.count%></small> 
            <p class="card-text">Friends: <small class="text-muted"><%= @user.friends.count%></small></p> 
        
                <% if current_user == @user %>
                    <%=link_to "Edit Profile", edit_user_registration_path%>
                <% end %>

                <% if current_user == @user %>
                <% elsif current_user.friends_with?(@user)%>
                    <%= link_to "Remove Friend", friends_remove_path(id: @user.id), method: :post, class: "btn btn-warning" %>
                <% elsif current_user.pending_friends.include?(@user)%>
                    <%= link_to "Request Pending!", '#', class: "btn btn-secondary" %>
                <% elsif current_user.requested_friends.include?(@user) %>
                    <%= link_to "Accept Friend Request", friends_accept_path(id: @user.id), method: :post, class: "btn btn-success" %>
                <% else%>
                    <%= link_to "Add Friend", friends_path(id: @user.id), method: :post, class: "btn btn-primary" %>
                <% end %>         
        </div>
</div>

app/views/users/index.html.erb
<h3> Explore New Friends! </h3>

<div class="row row-cols-1 row-cols-md-3">
    <div class="col mb-4">

        <% @users.each do |user| %>
        <% next if user.id == current_user.id %>
            <div class="card mb-1">
            <div class="row">
                <div class="col-sm-auto">
                    <% if user.profile_pic.attached? %>
                        <img src="<%=(url_for(user.profile_pic))%>", class="image-size">
                    <% else %>
                        <img src="https://bulma.io/images/placeholders/64x64.png">
                    <% end %>
                </div>
                <div class = "col">
                    <h5 class="card-title"><%= user.name %></h5>
                </div>
            </div>
            <div class="card-body">
                <% if current_user.friends_with?(user)%>
                    <%= link_to "Remove Friend", friends_remove_path(id: user.id), method: :post, class: "btn btn-warning" %>
                <% elsif current_user.pending_friends.include?(user)%>
                    <%= link_to "Request Pending!", '#', class: "btn btn-secondary" %>
                <% elsif current_user.requested_friends.include?(user) %>
                    <%= link_to "Accept Friend Request", friends_accept_path(id: user.id), method: :post, class: "btn btn-success" %>
                <% else%>
                    <%= link_to "Add Friend", friends_path(id: user.id), method: :post, class: "btn btn-primary" %>
                <% end %>
                    <%= link_to "View Profile", user, class: "btn btn-primary"%>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
        <%= render 'profile' %>
    </div>
    
    <div class="col-6">
        <div class="row mb-3">
        <% if current_user == @user %>
          <%= render 'posts/form', post: @post %>
        <% end %>
        </div>

        <div class="row"> 
          <%= render 'posts/feed', posts: @posts %>
        </div>
    </div>

    <div class="col text-center">
        <% render 'notifications' %>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>