config/routes.rb
Rails.application.routes.draw do
  root "posts#index"
  match '/users',   to: 'users#index',   via: 'get'
  match '/users/:id',     to: 'users#show',       via: 'get'
  get "/pages/:page" => "pages#show", :controller => 'pages', :action => 'show', :as => 'my_page'

  devise_for :users, :controllers => {registrations: "registrations", omniauth_callbacks: 'users/omniauth_callbacks' }, :path_prefix => 'd'
  #devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }


  resources :users, :only =>[:show]
  resources :posts
  resources :friends, only: [:index, :create]
  
  
  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :posts do
    resources :likes, :comments
  end
  
  post "/friends/accept" => "friends/accept"
  post "/friends/decline" => "friends/decline"
  post "/friends/remove" => "friends/remove"
  post "/friends/block" => "friends/block"
  post "/friends/unblock" => "friends/unblock"


 
  


end




#resources friends?

app/models/post.rb
class Post < ApplicationRecord

    belongs_to :user
    has_many :comments, dependent: :destroy
    has_many :users, through: :comments
    accepts_nested_attributes_for :comments

    has_many :likes, dependent: :destroy
    

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order("created_at DESC")
    @post = Post.new
    @comment = Comment.new(post_id: params[:post_id])
    @users = User.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = current_user.posts.build
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to root_path, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:post)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_comments.html.erb
<% @comments = post.comments.all %>
            <% @comments.each do |c| %>
            <%= c.body %>
<% end %>

app/views/posts/_feed.html.erb
<% @posts.each do |post| %>
    <% if current_user.friends.include?(post.user) || post.user == current_user %>
<div class="card mb-3"> 
    <div class= "row mt-1 mb-1">
        <div class="col-sm-auto no-gutters">
            <% if post.user.profile_pic.attached? %>
                <img src="<%=(url_for(post.user.profile_pic))%>", class="image-size">
            <% else %>
                <img class="rounded-circle" src="https://bulma.io/images/placeholders/64x64.png">
            <% end %>
        </div>
        <div class="col-6 text-left">
            <strong><%= link_to post.user.name, user_path(id: post.user.id), class: "deco-none" %> </strong><br>
            <small> <%= post.created_at.to_date %></small>
        </div>
    
        <% if user_signed_in? && current_user.id == post.user.id%>

        <%# testing dropdown menu %>
        <%# <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                ...
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="#">Action</a>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
            </div>
        </div>
        %>

            <div class="col btn-group-sm mr-2" role="group" aria-label="Second group">         
                <button type="button" class="btn btn-secondary"><%= link_to post do %>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-link-45deg" fill="white" xmlns="http://www.w3.org/2000/svg">
                        <path d="M4.715 6.542L3.343 7.914a3 3 0 1 0 4.243 4.243l1.828-1.829A3 3 0 0 0 8.586 5.5L8 6.086a1.001 1.001 0 0 0-.154.199 2 2 0 0 1 .861 3.337L6.88 11.45a2 2 0 1 1-2.83-2.83l.793-.792a4.018 4.018 0 0 1-.128-1.287z"/>
                        <path d="M6.586 4.672A3 3 0 0 0 7.414 9.5l.775-.776a2 2 0 0 1-.896-3.346L9.12 3.55a2 2 0 0 1 2.83 2.83l-.793.792c.112.42.155.855.128 1.287l1.372-1.372a3 3 0 0 0-4.243-4.243L6.586 4.672z"/>
                        </svg>
                    <% end %> 
                </button>
        

                <button type="button" class="btn btn-secondary"><%= link_to edit_post_path(post) do %>
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="white" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                        </svg>
                    <% end %> 
                </button>
                    
                    <button type="button" class="btn btn-secondary"><%= link_to post, method: :delete, data: { confirm: 'Are you sure?' }  do %>
                            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="white" xmlns="http://www.w3.org/2000/svg">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
                            </svg>
                        <% end %> 
                    </button>
        
            </div>   
            <% else %>
                <div class="col">

                </div>
            <% end %>         
    </div>
    
    <div class= "row">
        <div class="col">
            <div>
                <div>
                    <%= post.post %>
                </div>
            </div>
        </div>
    </div>

        <div class="row">
            <div class= "col tet-left">
                <p>
                    <small> <%= post.likes.count %> <%= (post.likes.count) == 1 ? 'Like' : 'Likes'%> </small>
                </p>
            </div>

            <div class= "col text-right">
                <small> <%= post.comments.count %> <%= (post.comments.count) == 1 ? 'Comment' : 'Comments'%> </small>
            </div>

        </div>
        <div class="btn-group mb-1">
        <% if user_signed_in? %>  
                <% pre_like = post.likes.find { |like| like.user_id == current_user.id} %>
                
                <% if pre_like %>
                    <%= link_to post_like_path(post, pre_like), method: :delete, class: "btn btn-outline-secondary" do %> 
                        <span class="icon"><i class="fa fa-thumbs-down" aria-hidden="true"></i></span>
                    <% end %>

                <% else %>
                    <%= link_to post_likes_path(post), method: :post, class: "btn btn-outline-secondary" do %> 
                        <span class="icon"><i class="fa fa-thumbs-up" aria-hidden="true"></i></span>
                    <% end %>
                <% end %>
        <% end %>
            <%= link_to "Comment", "#", class: "btn btn-outline-secondary" %>
        </div>

    <div class="row mb-1">
        <div class="col">
            <% post.comments.each do |c| %>
                <div class="card mb-1">
                    <div class= "row no-gutters align-items-center">
                        <div class="col-md-auto">
                            <img class="rounded circle" src="https://bulma.io/images/placeholders/32x632.png">
                        </div>
                        <div class="col text-left">
                            <small> <%= link_to c.user.name, user_path(id: c.user.id), class: "deco-none" %> </small>
                            <br>
                            <%= c.body %>
                        </div>
                    </div>                
                </div>
            <% end %>
                <% comment = Comment.new %>
                <%= render partial: "comments/form", locals: { comment: comment, post: post } %>
        </div>
    </div>
        
</div>
<% end %>
<% end %> 

app/views/posts/_find_friends.html.erb
<div class="card" style="width: 18rem;">
    <div class="card-header">
        Find New Friends
    </div>
    <ul class="list-group list-group-flush text-left">
        <% @users.limit(3).each do |user| %>
        <% next if current_user.id == user.id %>
        <% next if current_user.friends_with?(user)%>
        <% next if  current_user.requested_friends.include?(user) %>
        <% if current_user.pending_friends.include?(user)%>
            <li class= "list-group-item">
                <%= link_to user.name, user, class: "btn btn-outline-primary btn-sm"%>
                <%= link_to "Request Pending!", '#', class: "btn btn-secondary btn-sm" %>
            </li>
        <% else %>
            <li class= "list-group-item"> 
            <%= link_to user.name, user, class: "btn btn-outline-primary btn-sm"%>
            <%= link_to "Add Friend", friends_path(id: user.id), method: :post, class: "btn btn-primary btn-sm" %>
        </li>
        <% end %>
        <% end %>
        <%=link_to "View All", users_path, class: "list-group-item" %>
    </ul>
</div>

app/views/posts/_form.html.erb
  <%= simple_form_for(@post) do |f| %>
    <%= f.error_notification %>
      <%= f.input :post, label: false, input_html: { class: "textarea"}, wrapper: false, label_html: {class: "label"}, placeholder: "What's on your mind, #{current_user.name}?", autofocus: true %>
      <div class= "mb-2"> </div>
      <%= f.button :submit, class: "btn btn-primary" %>  
  <% end %>

app/views/posts/_profile.html.erb
<div class="card mb-3">
    <div class= "card-body">
        <div class= "row no-gutters align-items-center">
            <div class="col-md-auto">
                <% if current_user.profile_pic.attached? %>
                    <img src="<%=(url_for(current_user.profile_pic))%>", class="image-size">
                <% else %>
                    <img class= "rounded-circle" src="https://bulma.io/images/placeholders/64x64.png">
                    <% end %>
            </div>
            <div class="col text-left">
                <h5 class="card-title"><%=current_user.name%></h5>
            </div>
        </div>

        <div class= "row no-gutters align-items-center">
            <div class="col-md-auto">
                <p class="card-text"><p class="font-weight-bold">Posts: <small class="text-muted"><%= current_user.posts.count%></small></p> 
            </div>
            <div class="col-md-auto">
                <p class="card-text"><p class="font-weight-bold">Friends: <small class="text-muted"><%= current_user.friends.count%></small></p> 
            </div>
        </div>
    </div>
</div>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="container">
  <div class="row">
    <div class="col text-center">
      <%= render "profile" %>
    </div>
    <div class="col-sm-6">
      <div class="row mb-3">
        <%= render 'form', post: @post %>
      </div>

      <div class="row">
          <%= render 'feed' %>
      </div>
    </div>
    <div class="col text-center">
        <%= render "find_friends"%>
    </div>
  </div>
</div>

<p id="notice"><%= notice %></p>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @post.post %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>